apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cd-runner-deploy
  namespace: next-kube-app
rules:
  - apiGroups: [""]
    resources:
      - pods
      - pods/log
      - services
      - configmaps
      - secrets
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources:
      - deployments
      - replicasets
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["networking.k8s.io"]
    resources:
      - ingresses
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cd-runner-deploy
  namespace: next-kube-app
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cd-runner-deploy
subjects:
  - kind: ServiceAccount
    name: cd-runner
    namespace: deploy
